export enum ActionType {
  SEARCH_FETCH_DATA_SUCCESS = "SEARCH_FETCH_DATA_SUCCESS",
  SEARCH_FETCH_DATA_PENDING = "SEARCH_FETCH_DATA_PENDING",
  SEARCH_FETCH_DATA_ERROR = "SEARCH_FETCH_DATA_ERROR",
  RESET_STATE = "RESET_STATE",
  INCREMENT_PAGE = "INCREMENT_PAGE",
}
