export enum ActionType {
  SEARCH_FETCH_COLLECTION_SUCCESS = "SEARCH_FETCH_COLLECTION_SUCCESS",
  SEARCH_FETCH_COLLECTION_PENDING = "SEARCH_FETCH_COLLECTION_PENDING",
  SEARCH_FETCH_COLLECTION_ERROR = "SEARCH_FETCH_COLLECTION_ERROR",
  RESET_STATE = "RESET_SEARCH_COLLECTION_STATE",
  INCREMENT_PAGE = "INCREMENT_SEARCH_COLLECTION_PAGE",
}
