export enum ActionType {
  FETCH_EXPLORE_FEED_SUCCESS = "FETCH_EXPLORE_FEED_SUCCESS",
  FETCH_EXPLORE_FEED_PENDING = "FETCH_EXPLORE_FEED_PENDING",
  FETCH_EXPLORE_FEED_ERROR = "FETCH_EXPLORE_FEED_ERROR",
  RESET_EXPLORE_STATE = "RESET_EXPLORE_STATE",
  INCREMENT_EXPLORE_PAGE = "INCREMENT_EXPLORE_PAGE",
}
