export enum ActionType {
  FEED_FETCH_DATA_SUCCESS = "FEED_FETCH_DATA_SUCCESS",
  FEED_FETCH_DATA_PENDING = "FEED_FETCH_DATA_PENDING",
  FEED_FETCH_DATA_ERROR = "FEED_FETCH_DATA_ERROR",
  RESET_FEED_STATE = "RESET_FEED_STATE",
  INCREMENT_FEED_PAGE = "INCREMENT_FEED_PAGE",
}
